### ISSUE TITLE
Docker Compose Build doesn’t work for me

### ISSUE THREAD

**Issue by Thatoneshuppet** [Ballsdex-Team/BallsDex-DiscordBot#108]
Whenever I type “docker composer build”, it says “yaml: line 11: mapping values are not allowed in this context”.

**Comment by CommunistDex** [comment]
docker compose up -d

**Comment by CommunistDex** [comment]
> Whenever I type “docker composer build”, it says “yaml: line 11: mapping values are not allowed in this context”.

sex

**Comment by Thatoneshuppet** [comment]
I put “docker compose up -d” and it still says the same thing

**Comment by laggron42** [comment]
Your config.yml file is in the wrong format, use an editor like Visual Studio Code that will show you the errors you have. You can also check the wiki for a full example of a correct format.
