### ISSUE TITLE
Inaccurate flags

### ISSUE THREAD

**Issue by Novvelian** [Ballsdex-Team/BallsDex-DiscordBot#112]
The spawn art for New Zealand has a red star underneath the union jack, but the New Zealand flag doesn't have a start there, Australia does though. Also, I've been told the Mauritania flag is out of date since they added red stripes to the top and bottom of their flag recently. Also, the spawn art of Honduras is incorrect since they changed their flag colour to a lighter blue, as seen in their card art.

**Comment by parallelogra-windmill** [comment]
The Mozambique flag is also incorrect, as the book, hoe and rifle are not seen on the yellow star in the chevron (if I recall correctly).

**Comment by pppdjgw** [comment]
Yes

**Comment by Platformer444** [comment]
The Poland Flag too which has its colours' position flipped

**Comment by laggron42** [comment]
These issues are for the bot's core files, not the content of Ballsdex. Can you open a ticket in the [main server](https://discord.gg/ballsdex) so that we can take a look to that?

> The Poland Flag too which has its colours' position flipped
This is correct, Polandballs rules state that Poland should be flipped.
