### ISSUE TITLE
Commands - /balls completion

### ISSUE THREAD

**Issue by uamapps** [Ballsdex-Team/BallsDex-DiscordBot#114]
When i run /balls completion, it shows me only the progress. and it doesnt show me emojis that were added.
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/129000915/852419df-fa72-419b-bcce-999e3ea5eb50)

**Comment by laggron42** [comment]
The emoji IDs you have used are invalid, please check again these values in the admin panel. There is a guide in the wiki showing you how to correctly obtain emoji IDs (right clicking does NOT work, it copies the message ID).
