### ISSUE TITLE
500 Error in Admin Panel while making a new Ball

### ISSUE THREAD

**Issue by FoxyCantCode** [Ballsdex-Team/BallsDex-DiscordBot#119]
So recently I have started to make my own bot using your open source code and stuff, which I really appreciate btw. But when I went to localhost site and created a new ball, the Site just shows the Error

500
Oops... You just found an error page

And then return_home button just sends me back to admin panel

I don't know if this has been issued but help will be thankful

Thank you!

**Comment by flaree** [comment]
Please join the support server found within the readme, you can receive help there.
