### ISSUE TITLE
El laggron or the ballsdex team can you fix tradelocked bug i cant decline or accept and i cant give away my tradelocked ball so can you fix it?

### ISSUE THREAD

**Issue by kokoisreal** [Ballsdex-Team/BallsDex-DiscordBot#122]
El laggron or the ballsdex team can you fix tradelocked bug i cant decline or accept and i cant give away my tradelocked ball so can you fix it?

**Comment by flaree** [comment]
It'll be fixed whenever we have time, this is all volunteer based. Check out announcements channel for more info
