### ISSUE TITLE
ballsdex-discordbot-bot-1 exited with code 1

### ISSUE THREAD

**Issue by duckiecomrade** [Ballsdex-Team/BallsDex-DiscordBot#125]
I need someone to help me with the 'ballsdex-discordbot-bot-1 exited with code 1' error. I am new to self-hosting and have little to no experience. I read the guide (https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Installing-Ballsdex) and can't get my bot is work nor go online.

**Comment by BritMapping** [comment]
Attach the file

**Comment by duckiecomrade** [comment]
What file? The config.yml file?
