### ISSUE TITLE
Feature request: Add some bonuses for gathering a group of cards

### ISSUE THREAD

**Issue by LeviPesin** [Ballsdex-Team/BallsDex-DiscordBot#126]
Like continents (Europe, Asia, etc), union cards (USSR, UN, etc), or regions (Baltic countries, Scandinavia, etc).

**Comment by itzdilavids** [comment]
countries like Timor leste and Brunei, empires cards (Sultanate Malacca Empire,Majaphit etc) continent like ASEAN

**Comment by flaree** [comment]
We won't be adding in bonuses like this, however for achievements we hope to make this customizable.
