### ISSUE TITLE
Error 500 even though all the values were correct and I did nothing wrong

### ISSUE THREAD

**Issue by Ariezzzzdadjiboudexguy** [Ballsdex-Team/BallsDex-DiscordBot#133]
I am pretty sure

**Comment by Ariezzzzdadjiboudexguy** [comment]
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/140893331/5214f04a-36d9-4790-b2ed-45acd38bbd45)
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/140893331/f08b787a-8b69-4bbc-bfe0-97fdd0e1178c)
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/140893331/98d640ee-65d7-4600-83d1-eda115ca06af)
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/140893331/296e1a1a-70db-4679-aac4-cff4797c57f6)

**Comment by Ariezzzzdadjiboudexguy** [comment]
That popped up in docker

**Comment by Ariezzzzdadjiboudexguy** [comment]
Only started happening since 2.7.0

**Comment by flaree** [comment]
Rarity just be between 0-1

**Comment by Ariezzzzdadjiboudexguy** [comment]
> Rarity just be between 0-1

What do you mean? This isn't a special event!

**Comment by flaree** [comment]
Rarity has always been between 0-1, it would always error if it wasn't. Join the support server for further help

**Comment by Ariezzzzdadjiboudexguy** [comment]
> Rarity has always been between 0-1, it would always error if it wasn't. Join the support server for further help

That just seems insane! The rarity did nothing wrong. The regime is!
