### ISSUE TITLE
Include the balls's stats (attack and defence) in the "You caught a ball!" message. (Enhancement)

### ISSUE THREAD

**Issue by SecretaryBird** [Ballsdex-Team/BallsDex-DiscordBot#140]
### Include the balls's stats (attack and defence) in the "You caught a ball!" message.
I think it would be a good idea to show the ball's stats because it would remove the hassle of having to use a command to see the ball's stats.

The message could look like this:

> You caught Andorra! (#1712AEC)
> ATK: 182 (-3%) HP: 411 (-5%)
> 
> [event ball]
> 
> This is a new countryball that has been added to your completion!

**Comment by SecretaryBird** [comment]
misclick

**Comment by issquishfeminine** [comment]
that's really cool
