### ISSUE TITLE
[SUGGESTION] Make it so that other owners or team members can access localhost, not only the bot hoster without leaking IP

### ISSUE THREAD

**Issue by Ariezzzzdadjiboudexguy** [Ballsdex-Team/BallsDex-DiscordBot#141]
I think you can make it like localhost:8000/admin/c9eSGWcDO like that (last part was random)

**Comment by flaree** [comment]
Port forward the IP

**Comment by Ariezzzzdadjiboudexguy** [comment]
> Port forward the IP

what? i dont get it?

**Comment by flaree** [comment]
This is on you to find out as it has to do with your hosting and your network. We will not provide help for this
