### ISSUE TITLE
"bot-1" gets exited immediately after running

### ISSUE THREAD

**Issue by orange567gh** [Ballsdex-Team/BallsDex-DiscordBot#148]
As soon as I run the container, all of the items work except for "bot-1" which is crucial for getting the bot online. I've asked other self-hosted bot owners, and they can't seem to find out the reason.

**Comment by orange567gh** [comment]
It also says "created" when I run `docker compose up`.

**Comment by flaree** [comment]
We no longer offer self host support. We have a support server found in the readme in which you can seek help from the community.
