### ISSUE TITLE
/balls last takes 10 years to load is there a fix or its a skill issue from me

### ISSUE THREAD

**Issue by ghost** [Ballsdex-Team/BallsDex-DiscordBot#149]

**Comment by flaree** [comment]
Is this on Ballsdex of a self hosted bot?

**Comment by 1shotkillsniperstrikeshot** [comment]
self hosted

**Comment by laggron42** [comment]
It's probably your computer having a hard time generating the image (CPU problem), or uploading it to Discord (network problem).

Try using the "Generate card" button in the admin panel, next to the list of balls. If it takes a long time to process, your CPU is too slow.

You can also try using `/balls list` or `/balls info`, see if it also takes a long time. In that case, it's probably your network that is too slow.

**Comment by 1shotkillsniperstrikeshot** [comment]
> It's probably your computer having a hard time generating the image (CPU problem), or uploading it to Discord (network problem).
> 
> Try using the "Generate card" button in the admin panel, next to the list of balls. If it takes a long time to process, your CPU is too slow.
> 
> You can also try using `/balls list` or `/balls info`, see if it also takes a long time. In that case, it's probably your network that is too slow.

its probably my network my CPU is i7700k  

when i try tho it takes like 20% but gonna try your solution then reply again

**Comment by 1shotkillsniperstrikeshot** [comment]
> It's probably your computer having a hard time generating the image (CPU problem), or uploading it to Discord (network problem).
> 
> Try using the "Generate card" button in the admin panel, next to the list of balls. If it takes a long time to process, your CPU is too slow.
> 
> You can also try using `/balls list` or `/balls info`, see if it also takes a long time. In that case, it's probably your network that is too slow.

used /balls list was fast 
used /balls info was fast

tried 
/balls last took long time but at the end worked but the CPU usage with 
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/86213279/2991cd70-500e-461b-a61d-240d49183a4e)

**Comment by laggron42** [comment]
Just to check, how many balls do you (or the user running `/balls list`) have?

**Comment by 1shotkillsniperstrikeshot** [comment]
> Just to check, how many balls do you (or the user running `/balls list`) have?

3

**Comment by 1shotkillsniperstrikeshot** [comment]
> Just to check, how many balls do you (or the user running `/balls list`) have?

uh helo u forgot me

**Comment by flaree** [comment]
cannot replicate, closing
