### ISSUE TITLE
Error 500, can't add new balls

### ISSUE THREAD

**Issue by XxNinoviumxX** [Ballsdex-Team/BallsDex-DiscordBot#155]
I'm the maker of Dino Dex and whenever I try to add new dinosaurs now it just says "500" and then says there's an issue with the website.
![Screenshot 2023-10-08 103026](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/147302869/e4f19c66-7126-455a-a538-db2a0f6bc121)

this has only been happening recently, ever since i added the 20th dinosaur. Is 20 "balls" the limit for like, a free trial? Do we have to pay in order to add more "balls"?

**Comment by flaree** [comment]
Hi, the issue is with one of the values you are putting in.

Join the self host support server found in the readme for further help.
