### ISSUE TITLE
Balls power do not work

### ISSUE THREAD

**Issue by patronuscharm501** [Ballsdex-Team/BallsDex-DiscordBot#173]
All the cards have the abilities on them, however when we use them in battle the powers don't activate. For example: Reichtangle is designed to do 100 to 1000 damage of the user's choice. However, while in battle the Reichtangle is only doing 1 damage. This is happening with all balls, none are doing their abilities.

**Comment by flaree** [comment]
Abilities are not included in this pre-release version of battle, this is known behavior
