### ISSUE TITLE
Can't Get Balls

### ISSUE THREAD

**Issue by SansIsTheBest** [Ballsdex-Team/BallsDex-DiscordBot#183]
Aball appeared that was white in the top, blue in the middle, and red on the bottom. I put the name Russia into the button to catch and it said that it's wrong. then I opened the balls completion list, and I found a flag exactly the same called RUSSIA. but it still didn't work. then I searched up white blue and red flag on google and It gave me russia, but is STILL didn't work. so i input the name russia into the dex like 10 other times and it didn't work. I tried refreshing the page and it still didn't work. Can i please  have some help.

**Comment by flaree** [comment]
Join our support server found in the readme
