### ISSUE TITLE
Adding role/ guild ID's crashes the bot

### ISSUE THREAD

**Issue by the1eclipse** [Ballsdex-Team/BallsDex-DiscordBot#203]
2024-01-30 18:01:33 expected <block end>, but found '<block mapping start>'
2024-01-30 18:01:33   in "<unicode string>", line 47, column 3:
2024-01-30 18:01:33       guild-ids: - 1193663150487257099
2024-01-30 18:01:33       ^

**Comment by the1eclipse** [comment]
CODE: # enables the /admin command
admin-command: admin

  # all items here are list of IDs. example on how to write IDs in a list:
  # guild-ids:
  #   - 1049118743101452329
  #   - 1078701108500897923

  # list of guild IDs where /admin should be registered
  guild-ids: - 1193663150487257099

  # list of role IDs having full access to /admin
  root-role-ids: - 1193665264278065262

**Comment by flaree** [comment]
It doesn't crash, your config is incorrect.

**Comment by the1eclipse** [comment]
> your config is incorrect.

how do i fix it though
