### ISSUE TITLE
i have this one issue where i put the token in,and when i do docker compose up it still asks me to put the token in again so it basically doesnt see it

### ISSUE THREAD

**Issue by kuswastaken** [Ballsdex-Team/BallsDex-DiscordBot#206]
sup laggron im pretty sure you remember me from before as kus,the owner of historyballsdex
im planning on bringing historyballs'dex back to have fun again,but i have this one issue where even tho i put the token in,it asks me to put it in again

**Comment by MaxxMXSZ** [comment]
Don't forget Compose build.

**Comment by kuswastaken** [comment]
> Don't forget Compose build.
i did compose build,still doesnt work

**Comment by flaree** [comment]
we do not support self hosting, if its not working then its something on your end.
