### ISSUE TITLE
Updating config.yml issue 

### ISSUE THREAD

**Issue by MrCommander-1** [Ballsdex-Team/BallsDex-DiscordBot#207]
![Zrzut ekranu (289) edit](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/158770390/80942be6-b1e3-44db-93cc-87cadccc4855)
![Zrzut ekranu (290)](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/158770390/7a26113c-20c2-498e-9f97-86fc28efe3e3)
While im trying to uptade config.yml file (i want to get access to /admin commands like /admin spawn), then pulling this updates with git pull and restarting bot this thing shows (also bot don't turn on). I put in first this /admin stuff line my server id, then two times role on that server id (in second and third line) Is there a way to update config.yml without this thing appearing?

**Comment by MaxxMXSZ** [comment]
If you follow the docs correctly then it gonna have no problem so read it again

**Comment by ltzmax** [comment]
That's something on your end. we do not support selfhosting.
I also ask that you change your token as you just put it out here.

**Comment by kuswastaken** [comment]
the config.yml file is badly formatted,contact me on discord to help fix this issue
._kus
