### ISSUE TITLE
Localhost not working

### ISSUE THREAD

**Issue by xirinplayz** [Ballsdex-Team/BallsDex-DiscordBot#209]
I followed ALL of the instructions, so when I got up to the admin configuring page, I went to the localhost8000 thing the creator was talking about. However, it just says "500 oops... you just found an error page. We are sorry but we encountered an internal error." No matter what I do, it just keeps opening this error page. I need help.

**Comment by MaxxMXSZ** [comment]
You did something wrong try again.

**Comment by ltzmax** [comment]
Follow the wiki correctly how you enter into localhost. We also do not support selfhost.
