### ISSUE TITLE
Interaction timeout??, why!

### ISSUE THREAD

**Issue by HiboMan** [Ballsdex-Team/BallsDex-DiscordBot#229]
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/142530154/9a8b24dc-d8fe-400a-82cb-a6c45029ad93)
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/142530154/d3ebf3fc-e7cc-45c5-962f-19943394675f)
Whats going on
this happened out of nowhere to a bot im hosting

**Comment by MaxxMXSZ** [comment]
we don't support selfhosting but change your computer time you are hosting to automatic it probably caused by daylight saving

**Comment by laggron42** [comment]
The warning you see is correct. Discord only gives bot 3 seconds to acknowledge interactions, past that you will get a 404 error.

I added some code to immediately ignore interactions that are arriving too late and avoid taking the time to process a command that will fail anyway. So, to recap, the problem isn't on the code, it's your computer that is receiving the interaction too late, you may have network issues or your host is too slow to answer fast enough.

If your bot has a really big scale and runs at least 150 shards (which I don't believe is the case), you could look into clustering.
