### ISSUE TITLE
"Tortoise-ORM shutdown" error

### ISSUE THREAD

**Issue by AngerRandom** [Ballsdex-Team/BallsDex-DiscordBot#230]
Hey! I was tried to host Ballsdex without Docker. I was almost done but when I try to start the bot it fails to connect to database and gives this error (I cannot copy paste the full message there so I'll only send the error message):
`[2024-04-03 17:14:48] INFO tortoise: Tortoise-ORM shutdown`
Is there any way to fix it? I was found an issue similiar to this but I cannot found any solution and the support server in the readme says you end the support of self hosting.

**Comment by laggron42** [comment]
Hi, we indeed stopped supporting custom instances because it was too much of a drain, so you're mostly on your own unless you have problems that are legit and/or poorly documented.

The line of log you have included doesn't help at all, it's always displayed to indicate that the bot is shutting down. The relevant error is probably above. Feel free to include all the logs, or if you don't want to pollute too much you could use https://gist.github.com

**Comment by AngerRandom** [comment]
[ballsdex.log](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/files/14855873/ballsdex.log)
Okay then I'll send the log file itself then. (Don't mind the first logs, only check the last 2 log entries.)

**Comment by laggron42** [comment]
The error is printed in your console when this happens. I'm not sure where the other error comes from, but you should see this message in red which explains the issue
<img width="501" alt="image" src="https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/23153234/a428b701-b4a8-4561-8497-a363643f7272">

You need to export the `BALLSDEXBOT_DB_URL` environment variable when running the bot, to tell it how to connect to the postgres server.
For example, you could provide it with this value: `BALLSDEXBOT_DB_URL=postgres://ballsdex:defaultballsdexpassword@localhost:5432/ballsdex` (which is what is being used for the docker config). It attempts to connect to the database `ballsdex` with user `ballsdex` and the associated password.

You need to run a PostgreSQL server yourself, and learn to configure a user and database such that Ballsdex can connect to it. I can't help further with those issues, as this is out of scope of our code.

**Comment by AngerRandom** [comment]
Actually that error was logged before I set up the PostgreSQL server correctly. I have that already. Probably you checked the first error message.

**Comment by AngerRandom** [comment]
I think it finally connected to database after setting up my own database.

**Comment by laggron42** [comment]
This is an error with your config file. I'm closing at this point because this is stuff you can find in the docs, or by using a YAML validator.
