### ISSUE TITLE
I have 2-3 problems

### ISSUE THREAD

**Issue by AngerRandom** [Ballsdex-Team/BallsDex-DiscordBot#233]
I'm really sorry for opening too much issues but this time I need some answers for 2-3 issues:
1. How can I start the admin panel after starting the bot? After starting the bot it won't let me to run commands anymore so I cannot start the admin panel.
2. How can I shutdown/restart the bot? I tried the CTRL+C method but it's not working (Reason is probably im using a hosting service and I'm on a mobile phone). And when I restart the panel without shutting down the bot probably it won't let me to start the bot again anymore.
3. I tried to create/delete custom ball by using the `/admin` commands but when I delete a ball it still exist on the completion. And when I try to display that ball on a different command it say the ball does not exist. Reloading cache didn't worked. How can I fix this?
If you think these 3 issues' solution available in the docs, you can simply ignore this post.

**Comment by flaree** [comment]
You can find out how to run the panel here: https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Installing-Ballsdex#6-run-the-bot
cntr c/z will shut down the bot

admin balls delete only deletes an instance of a ball, to delete a ball you must goto the panel
