### ISSUE TITLE
Does admin panel works on mobile devices?

### ISSUE THREAD

**Issue by AngerRandom** [Ballsdex-Team/BallsDex-DiscordBot#237]
This question is kinda nonsense, but can Ballsdex bot admin panel run on mobile devices? Because when I started the bot and admin panel and tried to access to redis database (I thought it was probably the link to admin panel after starting the bot), it takes too long to load then it gives `ERR_TIMED_OUT` error. I tried to use a redis server instead of redis database but I get `ERR_INVALID_HTTP _RESPONSE` error this time. (Probably idk how to set up a redis server) You can simply ignore this post if you don't want to answer.

**Comment by kuswastaken** [comment]
lets hope that you get laggron to see this because he kind of helps actually, anyways as for this

i do not think its possible

**Comment by flaree** [comment]
We definitely do not support the running of this on any mobile device, we recommend using a dedicated server or your local PC.


If you mean the panel itself doesn't work on a mobile browser, then yes it is not mobile friendly.
