### ISSUE TITLE
While doing docker compose build my bot had this error

### ISSUE THREAD

**Issue by DaUkraine** [Ballsdex-Team/BallsDex-DiscordBot#238]
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/167307260/44069dd7-b5d7-412b-83b3-e1a79c6a6e16)

**Comment by flaree** [comment]
Can you actually show the error rather than cropping to half a sentence

**Comment by DaUkraine** [comment]
yes 1 sec

**Comment by DaUkraine** [comment]
![image (3)](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/167307260/a14ff10a-a3bc-4c68-b4a8-1453d98b288f)
its also been stuck for like 300 seconds now

**Comment by laggron42** [comment]
That's not the same error, and it doesn't have any details, there's nothing we can help with there. It looks like a Docker issue to me, not a bot issue tbh

**Comment by DaUkraine** [comment]
it doesnt give me the error anymore but its just stuck there
