### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by Kingofthehill4965** [Ballsdex-Team/BallsDex-DiscordBot#242]
So yeah I had an idea of having an economy and currency system in my dex as well as a shop. So yea..... I've already written the code. So yeah i just wanted to suggest it and I'm ready to share my code btw.

**Comment by flaree** [comment]
We do have plans of adding a currency, we just haven't gotten around to discussing how to earn them, what to spend them on, what stuff should be worth etc. Can you create a PR so we can have a look at your implementation?

**Comment by Kingofthehill4965** [comment]
So.... I just made simple economy commands like work, crime, roulette, income etc. like all economy bots have and also a shop so people can buy the collectibles. and alr I'll create a PR

**Comment by Kingofthehill4965** [comment]
Oh alr. Btw may i know what kind of currency system had been planned?
