### ISSUE TITLE
Can't battle

### ISSUE THREAD

**Issue by Ray-Hsueh** [Ballsdex-Team/BallsDex-DiscordBot#246]
I have recently used your system to create my own bot, which I am grateful for, but I would also like to ask why I can still see the battle command at the beginning, but then it disappears? I also can't find a place to adjust the battle settings.

**Comment by ltzmax** [comment]
This is not the battle mode that we intend to release the one you see on ballsdex. There is no ETA for the release of a battle mode as of yet. The current version will remain private to the Ballsdex only while it is tested and improved.
