### ISSUE TITLE
Commands keep not working at seemingly random times and take forever to work again.

### ISSUE THREAD

**Issue by KhaosOrganized** [Ballsdex-Team/BallsDex-DiscordBot#248]
I'm also getting an error whenever someone tries to put in a command whenever these random pockets of commands not working happen: WARNING  ballsdex.core.bot Skipping interaction 1237530895196356628, running 2.862331s late.

**Comment by MaxxMXSZ** [comment]
Common stuff mostly because your internet is slow

**Comment by Petrosado** [comment]
I have the same issue, do you have a fix?

**Comment by ltzmax** [comment]
> I have the same issue, do you have a fix?

There is not. you may try host the bot on a VPS.
