### ISSUE TITLE
Error regarding ballsdex. Dont know what this means...

### ISSUE THREAD

**Issue by ghost** [Ballsdex-Team/BallsDex-DiscordBot#256]
I'm not sure what this means and how to fix it. I've been having alot of **trouble here.**

**Comment by Florwa** [comment]
its been 3 days, can someone help?

**Comment by Florwa** [comment]
alright thank you!

**Comment by Florwa** [comment]
I didnt get a response.

**Comment by ltzmax** [comment]
While not much information is provided here, i am going to close this. We also do not support self-hosting bots. if you have any problem with docker, you may try reading the error and google or and ask the docker community.
