### ISSUE TITLE
add user arg to `/balls count`

### ISSUE THREAD

**Issue by gtm-nayan** [Ballsdex-Team/BallsDex-DiscordBot#259]
How I plan to use it:
Trading lots of common cards with other users on a marketplace server, need to check whether some user has enough balls that I need, how I do it now is use `/balls list` then manually count the balls, which is of course annoying and error-prone. 

Having a count command would make it easy to quickly gauge whether or not to pursue a discussion with this user.

PR: #258 

N.B. the support tickets I could find on the discord forum were closed as duplicates and the oldest one was closed with just a "no". If this feature is undesirable, would be nice to at least have it documented why somewhere with a better search than discord. 🙂

**Comment by flaree** [comment]
We do not want a user arg to count, the command is designed for a user to check their own count and that's all. It was intentionally omitted during the development of the command

**Comment by gtm-nayan** [comment]
I assume it was omitted because there was no utility seen for it at the time? Or was the use considered and not deemed valid?

**Comment by flaree** [comment]
Nope, intentionally omitted as it's a command that is used for checking your own count, not others. The admin command exists for checking other users, that is as far as it'll go in terms of allowing for such an addition
