### ISSUE TITLE
Ballsdex Issue. I can't seem to start the [docker-compose build]

### ISSUE THREAD

**Issue by Knn223** [Ballsdex-Team/BallsDex-DiscordBot#261]
I've been trying for a while now and it doesnt work.
I'm on the step "4. Installing the bot" part and I done everything, but this seems to not be working.
I tried to google it and research the problem, but nothing pops up.

![Issue](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/170281452/34d37b97-3249-4fd7-bd34-f0f434b47cae)

**Comment by ezykill10** [comment]
I know it says its closed but if you or anybody else is still having the problem run "docker login" and input your username and password from docker, worked for me!

**Comment by laggron42** [comment]
Huh that's weird, didn't know docker required login now
