### ISSUE TITLE
bot keeps leaving by its own in one specific guild

### ISSUE THREAD

**Issue by 0necell** [Ballsdex-Team/BallsDex-DiscordBot#265]
for no reason my bot keeps leaving in a specific guild (1011010967750054029). i've tried multiple times and even resetted the bot's token, but still nothing. what should i do?

**Comment by ltzmax** [comment]
You will have to enable `Public Bot` option on [developer portal](https://discord.com/developers/applications). Click on your bot then go to bot tab, it should be under there.

**Comment by 0necell** [comment]
> You will have to enable `Public Bot` option on [developer portal](https://discord.com/developers/applications). Click on your bot then go to bot tab, it should be under there.

its already enabled

**Comment by ltzmax** [comment]
Then i believe you have to check `/about`, if your bot is in 100, then it wont be able to join more than that until its verified.
I anyhow cannot repro the issue.
