### ISSUE TITLE
forgot password

### ISSUE THREAD

**Issue by PersonwhoownsYTDEX** [Ballsdex-Team/BallsDex-DiscordBot#273]
i forgot my password and i dont know what i have to run in the command terminal to get my account back, what do i do?

**Comment by laggron42** [comment]
`docker compose exec postgres-db psql -U ballsdex ballsdex -c 'TRUNCATE TABLE "user";'`

This removes all admins and unlocks the `/admin/init` URL again to create the first admin user.

**Comment by AdalbertTheCreator** [comment]
Thanks, I also had this problem.
