### ISSUE TITLE
Farms Control

### ISSUE THREAD

**Issue by Ray-Hsueh** [Ballsdex-Team/BallsDex-DiscordBot#283]
I would like to ask whether there is any planning in place to deal with behaviours such as the prevention and control of farms? This is because it seems that the only feasible way to do this is to use log monitoring or something like that. Have you considered developing any mechanism to prevent this?

**Comment by flaree** [comment]
We cannot make use of most of the mechanisms to prevent it as Ballsdex (the actual instance we run) cannot use the members intent. There are tools already available such as catch logging, admin tools and admin guilds for you to independently investigate.
