### ISSUE TITLE
cant start an battle

### ISSUE THREAD

**Issue by pessiiscool** [Ballsdex-Team/BallsDex-DiscordBot#295]
i cant start a battle while ive never even started one
![h](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/174028822/a8af95c5-cf96-413e-b631-afcf26555d37)

**Comment by laggron42** [comment]
Battles are not yet public and not in this repository, thus this issue is out of context.

Can you open a bug report in the appropriate channel in Discord instead? We will look into it.
