### ISSUE TITLE
admin commands dont work 

### ISSUE THREAD

**Issue by fazebigshak** [Ballsdex-Team/BallsDex-DiscordBot#306]
on docker it says the admin  command is too long,stripping description and on discord it says you are not allowed to use that command i put  the role id in and the server id in correctly but it still dont work

**Comment by ltzmax** [comment]
Hey,
You will need to have the role and it only works in the server you provided in the config.

You can also try server settings - integrations - select your bot and tap on admin, add the role there.

**Comment by fazebigshak** [comment]
> Hey, You will need to have the role and it only works in the server you provided in the config.
> 
> You can also try server settings - integrations - select your bot and tap on admin, add the role there.

it still doesnt work

**Comment by fazebigshak** [comment]
> Hey, You will need to have the role and it only works in the server you provided in the config.
> 
> You can also try server settings - integrations - select your bot and tap on admin, add the role there.

it still doesnt work
