### ISSUE TITLE
I can't create new admin

### ISSUE THREAD

**Issue by AdalbertTheCreator** [Ballsdex-Team/BallsDex-DiscordBot#307]
I am doing my AirlinesDex bot (where you can catch airlines), but I can't create admin account for me, because the site redirects me to http://localhost:5736/admin/login

**Comment by Ray-Hsueh** [comment]
use http://localhost:5736/init

**Comment by AdalbertTheCreator** [comment]
Not found

**Comment by AdalbertTheCreator** [comment]
![detail](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/165762967/07a53200-3dcc-4511-9068-b25dcf9735d5)

**Comment by Ray-Hsueh** [comment]
1. r u using the right port?
2. have you ever enter the admin panel?

**Comment by AdalbertTheCreator** [comment]
1. Yes
2. I can't access it because I can't create admin

**Comment by AdalbertTheCreator** [comment]
Redirects me to https://github.com/Ballsdex-Team/BallsDex-DiscordBot/issues/307
If it worked I wouldn't open this issue.

**Comment by laggron42** [comment]
Can you detail what you were trying to do, provide a step-by-step of what you did (the buttons you clicked, the data you filled, what you expect to happen...)

**Comment by AdalbertTheCreator** [comment]
Before changing the port I did what exactly was written in tutorial on wiki (https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Installing-Ballsdex)

**Comment by laggron42** [comment]
That's still not enough details, please put effort in your issue to actually help us helping you, right now it's impossible to troubleshoot anything.

> Before changing the port

How did you change it? provide the exact line(s) you modified

> I did what exactly was written in tutorial on wiki

*What* step exactly? Did you get a 404 when pressing the "Admin" button in the sidebar? Or when clicking the "Create" button?

Be verbose, include everything you can: logs, screen recording, detailed walkthrough, what you modified... Check [this issue] for an example of what a proper bug report is (I should add templates here, that's on me)

**Comment by AdalbertTheCreator** [comment]
I changed the port by editing "docker-compose" file, line 35 (on screenshot marked by red dot) after doing step 6 and then bulit the bot like it's shown in line 7 (it worked with previous bot). 
![line](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/165762967/ccd27992-c23b-4e4a-8ee2-6b35338f1db8)

**Comment by AdalbertTheCreator** [comment]
That was the order: 

1. I did first 6 steps of wiki. 
2. I changed "ports" value in docker-compose.yml file
3. I restarted the bot by "docker compose build", then "docker compose down" and "docker compose up"

**Comment by AdalbertTheCreator** [comment]
Unfortunately, I don't have any recordings of me creating the bot.

**Comment by AdalbertTheCreator** [comment]
I won't be able to do anything with my bot between 7th and 18th of July

**Comment by AdalbertTheCreator** [comment]
I created brand new bot (Port changed to 5055), but the issue is again happening. 
![Zrzut ekranu 2024-07-18 161452](https://github.com/user-attachments/assets/3dab9ef1-7a84-436e-85ab-d59990b1d1e5)

**Comment by AdalbertTheCreator** [comment]
imo the problem is false information about admin that don't actually exist.
