### ISSUE TITLE
Pluralization Support

### ISSUE THREAD

**Issue by flaree** [Ballsdex-Team/BallsDex-DiscordBot#310]
We need the ability to define in the config a way to define the plural string in which can be used when the word is plural.

- Add a new setting value (something along the lines of settings.collectible_plural_name)
- Replace instances of `{settings.collectible_name}s` with  settings.collectible_plural_name and drop the s
- Find any other occurrence where pluralization is needed

**Comment by Kingofthehill4965** [comment]
@flaree i'd like to do this

**Comment by flaree** [comment]
assigned to @imtherealF1
