### ISSUE TITLE
build: Python 3.12 Buster not found

### ISSUE THREAD

**Issue by HiboMan** [Ballsdex-Team/BallsDex-DiscordBot#312]
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/142530154/8fd1ce25-ff1f-498c-ac1d-0efcc5ae1964)
failed to solve: python:3.12-buster: docker.io/library/python:3.12-buster: not found
Bot will not start because of this, i have also looked up buster and it truly isnt found, ![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/142530154/e6e0a330-39b8-407b-881d-cc8567306af3)

**Comment by laggron42** [comment]
Oh oops, that's on me, replace with `3.12-bullseye` while I fix that. Forgot buster wasn't a thing anymore

**Comment by laggron42** [comment]
Fixed in 837acdd
