### ISSUE TITLE
Cannot restore from data-dump.sql

### ISSUE THREAD

**Issue by newzac0** [Ballsdex-Team/BallsDex-DiscordBot#315]
Okay so I was able to make a backup of my data but I have no idea how to restore from it now. Backup was made using [this tutorial](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/issues/245)

**Comment by Valen7440** [comment]
In powershell or bash, run this commands
```
docker exec -i CONTAINERNAME-postgres-db-1 psql -U ballsdex -d ballsdex -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
docker exec -i CONTAINERNAME-postgres-db-1 psql -U ballsdex -d ballsdex < data-dump.sql
```

**Comment by newzac0** [comment]
Thank you so much!
