### ISSUE TITLE
Add a command for showing all the balls that you have more than one of

### ISSUE THREAD

**Issue by VidTDM** [Ballsdex-Team/BallsDex-DiscordBot#319]

**Comment by Kingofthehill4965** [comment]
@VidTDM ??

**Comment by Kingofthehill4965** [comment]
you can just use `/balls list sort:duplicates`

**Comment by ltzmax** [comment]
Hello there. 
That's right said above here, you can use `/balls list sort:duplicates` to see all of your duplicate balls.
