### ISSUE TITLE
Cards not working.

### ISSUE THREAD

**Issue by Moaiwastaken** [Ballsdex-Team/BallsDex-DiscordBot#324]
So I’ve made a regime and the template seems to be glitching out whenever I make a new one. Only my first one works and any new ones I add are breaking, I’m using the card template normally provided, it causes the collection card to glitch out and it’s happening with every single one of the collection cards so I know it’s the regime. I’m just not sure how to fix this because nothings working, I don’t know if it’s a generation error or what.

**Comment by imtherealF1** [comment]
@Moaiwastaken by glitching out do you mean its making the command error, or is it way too big/small, hence it doesnt fit, which would mean that the dimensions are wrong?

**Comment by ltzmax** [comment]
Hey.
ensure that you have correct size of the cards, they're listed on the admin panel on newest version of the bot. Should something happen again, feel free to join the developer server. it's listed in the readme and we'll be able to help more!
