### ISSUE TITLE
Questions when making new dex

### ISSUE THREAD

**Issue by phantominor** [Ballsdex-Team/BallsDex-DiscordBot#328]
I have mainly 3 problems for now, hope someone can help me out on these difficult things><

1. It was working fine yesterday, but when I reopened my dex today, an error message appeared:

```Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8000 -> 0.0.0.0:0: listen tcp 0.0.0.0:8000: bind: An attempt was made to access a socket in a way forbidden by its access permissions.```

I have repeatedly used docker compose down - build - up several times, but this error still occurs, causing my admin panel to fail to open. Although the ball will still spawn normally and the commands can be used, the admin panel cannot be opened. What could be the problem?

2. How to force a specific rather than random ball to spawn?

3. How to hold an event with only a single ball, such as event France, event USA, etc.?

Thank you very much. Sorry to trouble you.

![Problem 1 error](https://github.com/user-attachments/assets/ebbd5388-2909-4e30-b228-162126b7078a)

**Comment by phantominor** [comment]
thanks a lot for your help @imtherealF1 !
But i have no idea how to do the codes of 1 day events >< Can you possibly give me a hint of that?
Thanks.

**Comment by imtherealF1** [comment]
@phantominor your welcome for the help, but I won't help with the code, sorry.

**Comment by phantominor** [comment]
tks, still appreciated.
