### ISSUE TITLE
/player stats command

### ISSUE THREAD

**Issue by imtherealF1** [Ballsdex-Team/BallsDex-DiscordBot#356]
A command that would show a lot of players stats, such as:
balls completion in %
the amount of countryballs you have
the amount of shiny countryballs you have (possibly)
the amount of trades done
and maybe more, i haven't thought of any more atm.
if this gets accepted i will make a pr for it.

**Comment by imtherealF1** [comment]
it can also show the amount of friends you have and the amount of users you've blocked, that's only when #340 gets merged

**Comment by flaree** [comment]
I've assigned this to you to create
