### ISSUE TITLE
/admin event create

### ISSUE THREAD

**Issue by imtherealF1** [Ballsdex-Team/BallsDex-DiscordBot#371]
**Describe the feature you'd like**
Similar to /admin balls create, it would allow admins with no access to the admin panel to create events.

**Additional context**
It would need many checks, so that the users can't put a start date that is after the end date etc.

**Comment by flaree** [comment]
I personally don't see a need to add this, I think the panel is enough

**Comment by imtherealF1** [comment]
I just think that since admin balls create exists, and since a lot of people don't know/want to port forward, resulting in only 1 person having panel access even if they want to give access to more functions to more people, it would be a good addition

**Comment by ltzmax** [comment]
> I just think that since admin balls create exists, and since a lot of people don't know/want to port forward, resulting in only 1 person having panel access even if they want to give access to more functions to more people, it would be a good addition

I am personally not a fan of that `admin balls create` at all. I never have made use of it, i use admin panel over this thing, it's so much easier, so i don't think this should be a command at all, It just takes up slash slots of something that i see will barely be used!

**Comment by laggron42** [comment]
Tbh the `/admin balls create` was there to make things faster for us with Patreon balls, I still think it's important to use the admin panel first and foremost. If we begin adding similar commands, people will keep asking for more: regime, economies, editing existing fields... For that reason, I won't be adding more stuff that can be done through the admin panel, it shouldn't be replaced.
