### ISSUE TITLE
Where's the card template and the symbols template? They just disappeared for me

### ISSUE THREAD

**Issue by Discord-snipemaster** [Ballsdex-Team/BallsDex-DiscordBot#394]
**Describe the bug**
I suddenly can't find the card and symbol templates, please help

I went to where it was supposed to be and it wasn't there.

**Comment by flaree** [comment]
Can you try not being so vague

**Comment by Discord-snipemaster** [comment]
Was that supposed to help me? I asked for help not "special support" now
where's the card and symbols templates

בתאריך יום ה׳, 12 בספט׳ 2024, 10:49, מאת Jamie ***@***.***>:

**Comment by flaree** [comment]
You're making it hard to help by being vague, but since you want to be a dick about it then i'll just close this.
