### ISSUE TITLE
After newest update /balls-give is not working

### ISSUE THREAD

**Issue by Nipatsuplayer** [Ballsdex-Team/BallsDex-DiscordBot#407]
**Describe the bug**
When users try to use command, it wont let them choose ball to give
**To Reproduce**
1. use command /balls-give
2. try to choose ball

**Expected behavior**
should show balls when u type but shows nothing

**Screenshots**
![image](https://github.com/user-attachments/assets/fdab66fd-b76d-47e7-abb0-6669b341a873)

**Version:**
 - 2.20.0

**Additional context**

**Comment by imtherealF1** [comment]
@Nipatsuplayer do you have any skins to actually give? and that looks like an issue on discord loading the autocomplete, not on the code.

**Comment by Nipatsuplayer** [comment]
@imtherealF1 yes i have. In image i searched with k and i have skin named k-might. Other users have same problem

**Comment by flaree** [comment]
Indeed there is currently an issue with the translations model we added, we hope to resolve this in the coming days.

**Comment by Nipatsuplayer** [comment]
okay, good

**Comment by flaree** [comment]
a fix was deployed
