### ISSUE TITLE
Friend list showing same friend twice

### ISSUE THREAD

**Issue by Nipatsuplayer** [Ballsdex-Team/BallsDex-DiscordBot#424]
**Describe the bug**
Friend list is showing same friend twice. My bot user found this and I think its bug
**To Reproduce**
1. use command /player friend list

**Expected behavior**
I think it should show same user only one time

**Screenshots**
![image](https://github.com/user-attachments/assets/79a0e0e8-d805-4257-be60-4b27f2893047)

**Version:**
 - 2.20.0

**Additional context**

**Comment by imtherealF1** [comment]
this only happens if you sent 2 friend requests in a row and both were accepted. #421 this pr will fix this issue, so in the next bot update this will be fixed.
