### ISSUE TITLE
My ballsdex collection deleted 

### ISSUE THREAD

**Issue by Mareking222** [Ballsdex-Team/BallsDex-DiscordBot#428]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Can be found in /about (applicable if self hosting)

**Additional context**

**Comment by Mareking222** [comment]
I had more than 55% of completition and my balls are gone
![IMG_20240923_120733](https://github.com/user-attachments/assets/10079647-ea8b-4d5e-b9f9-14463807005a)

**Comment by flaree** [comment]
read announcements in our server
