### ISSUE TITLE
BACKUP_DIR points to a file or folder with insufficient permissions.

### ISSUE THREAD

**Issue by ezykill10** [Ballsdex-Team/BallsDex-DiscordBot#431]
Whenever I start up my bot, everything starts up fine except for the ballsdex-discordbot-postgres-backup-1, it keeps spamming the cmd console with "BACKUP_DIR points to a file or folder with insufficient permissions." I searched through the files and I couldn't even find BACKUP_DIR, and I think this is related but my bot doesn't work. Whenever I run a command in discord the bot sends the message "The application did not respond." What do I do??

**Comment by laggron42** [comment]
That problem shouldn't hold the bot from starting, something else is happening. Look at the logs from the container `bot`, that's where the problem is

**Comment by ezykill10** [comment]
ok well it randomly fixed itself but now I got a new problem, I have my discord server listed as a guild id so I can use admin commands but the admin commands have the problem, application won't respond

**Comment by ezykill10** [comment]
nvm i had to add a role for it to work too im gonna close this now lmao
