### ISSUE TITLE
[admin] command or arg that allows an admin to edit a blacklist reason.

### ISSUE THREAD

**Issue by imtherealF1** [Ballsdex-Team/BallsDex-DiscordBot#433]
**Describe the feature you'd like**
A command, possibly named /admin blacklist edit, or an argument in an already existing command, that would allow an admin to edit the blacklist reason. Right now, if you need to edit it, you would need to remove the blacklist, and add it again, which can be annoying.

**Comment by flaree** [comment]
I don't personally think we need more commands just some something that can be done with two chained commands. Just a waste of a sub command slot imho

**Comment by imtherealF1** [comment]
there could be a re-write in admin commands, and e.g there would only be 1 command for blacklists, working with dropdowns ig? if thats not wanted, there could just be an argument in an already existing command for it

**Comment by flaree** [comment]
That just makes it more convulting to use as you can't just autocomplete the blacklist add or remove etc, i personally think it's fine the way it is
