### ISSUE TITLE
[trade] Add mandatory cooldown in between lock and confirm

### ISSUE THREAD

**Issue by flaree** [Ballsdex-Team/BallsDex-DiscordBot#443]
**Describe the feature you'd like**
Add a 15-30 second mandatory cooldown in between the actions of locking and confirming

This will give people time to double check their trade and just blindly confirm

**Comment by imtherealF1** [comment]
I would like that, I've seen many people just get "scammed", as they aren't careful and confirm the trade without noticing how something is missing in the proposal of the other user. I think it should be 15 seconds, and the response of the bot when the user tries to accept the trade during the cooldown should include the purpose of it, which is to double check the proposals.
