### ISSUE TITLE
Admin Panel issues

### ISSUE THREAD

**Issue by HiboMan** [Ballsdex-Team/BallsDex-DiscordBot#444]
Pages are invisible, I have to manually type in pages in the URL

I don't know how to reproduce this

I expected upon logging into the panel that it would work like always

Version: 2.20.0
![image](https://github.com/user-attachments/assets/6eed1ad1-deb5-4af5-b6b4-15cae0820800)
![image](https://github.com/user-attachments/assets/70227d74-ce05-4465-8300-0757d88f5039)

**Comment by HiboMan** [comment]
PC

**Comment by laggron42** [comment]
Refresh your poetry virtualenv, or rebuild the docker image. There is a [bug](https://github.com/fastapi-admin/fastapi-admin/issues/170) on the latest fastapi-admin version, idk how they still haven't fixed it. I pinned it to commit https://github.com/fastapi-admin/fastapi-admin/commit/ebea3bf71689caa583fe55aa25db899cf8eeae31

**Comment by HiboMan** [comment]
Thank you so much for the solution
I noticed something unrelated to my problem but here if you want to know
![image](https://github.com/user-attachments/assets/f742a6b5-ba52-4a0a-a27d-eaf90160343f)

**Comment by laggron42** [comment]
Looks like you renamed the folder, you're not supposed to do that

**Comment by HiboMan** [comment]
Nope the folder has the exact same name as the repo uses

**Comment by HiboMan** [comment]
No
They're completely untouched.
