### ISSUE TITLE
My Bot is not responding to slash commands at all no matter what but otherwise is working fine.

### ISSUE THREAD

**Issue by KhaosOrganized** [Ballsdex-Team/BallsDex-DiscordBot#449]
Whenever I or another user use a slash command for my dex bot my bot doesn't respond but my admin text based commands work and the bot seems to be running fine for catching and spawning as well.

The error message is the general "Skipping interaction X, running X.Xs" but it's running crazy late like 10.Xs late.

![Screenshot 2024-10-20 131037](https://github.com/user-attachments/assets/445fa074-747a-44fd-9cb1-858545ae1a4d)
![Screenshot 2024-10-20 131055](https://github.com/user-attachments/assets/3bdd84d7-a302-4080-80ba-96c23e8393b2)

latest version of the bot and docker

this is either a problem with the default code or my pc/internet, but either way, how do I fix it, i feel like I've tried everything and the bot doesn't seem to be even hitting it's limit of how much it can use at all.

**Comment by MaxxMXSZ** [comment]
Might be your internet indeed but try to check your computer if your time is synced that might be a problem too!

**Comment by KhaosOrganized** [comment]
time is synced?

**Comment by KhaosOrganized** [comment]
OMFG YOU DID IT, MY TIME WASN'T SYNCED
