### ISSUE TITLE
error when trying to install/configure the bot

### ISSUE THREAD

**Issue by LordAxolotl7** [Ballsdex-Team/BallsDex-DiscordBot#455]
![Capture3](https://github.com/user-attachments/assets/7b4ca126-9ee9-46cb-912b-a31933b29769)

followed the instructions at https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Installing-Ballsdex , and ended up stuck at part 4/5
putting in the commands in Powershell work initially, but at around 12/16 progress, this error is displayed in the console, and it stops installing/configuring
not sure what the error means or how to fix, says something about poetry config

**Comment by laggron42** [comment]
I'm aware of this error and working on a fix, sorry it's taking so long!
