### ISSUE TITLE
[player] Merging all 4 policy commands into 1, /player policy

### ISSUE THREAD

**Issue by imtherealF1** [Ballsdex-Team/BallsDex-DiscordBot#457]
**Describe the feature you'd like**
All the 4 policy commands to be merged into a command named /player policy. It would have one argument for each policy, allowing for bulk changes.

**Additional context**
I have the code for it ready, so I can make a PR for it.

**Comment by laggron42** [comment]
I'm not sure it's a good idea to merge those commands, eventually if we add a lot more commands under `/player` space, but right now I think the current interface is intuitive enough, nor overloaded.

**Comment by imtherealF1** [comment]
it isn't overloaded indeed, but in my eyes supporting bulk changes, that would also look nice and dynamic would give a better user experience. it would make changing all 4 policies at once much quicker, and can come in handy. i also think that /player policy or /player policies sounds better than just /privacy, /donation policy etc, ill attach a screenshot or two of how it can look.
![1](https://github.com/user-attachments/assets/c880a7bc-c30f-4520-aa3b-29c936e4165c)
![2](https://github.com/user-attachments/assets/328d0097-3c73-4bf7-96b9-67f8e8c9d5f2)
![3](https://github.com/user-attachments/assets/b3f11387-6912-44f4-9b3b-a0245074b7b9)

**Comment by laggron42** [comment]
I like this interface, but I still believe the `/player` command is not cluttered enough for that. So, I'll temporarily close this issue, but it will be brought back when we have too many `/player` subcommands (which will most likely happen, after some major updates)
