### ISSUE TITLE
Bug with friend policy after new update

### ISSUE THREAD

**Issue by Nipatsuplayer** [Ballsdex-Team/BallsDex-DiscordBot#466]
**Describe the bug**
When I use command _/player policy friends_ it says 

> An error occured when running the command. Contact support if this persists.

In console it says this: `column "friend_policy" does not exist`

**To Reproduce**
Use command _/player policy friends_

**Expected behavior**
It should do something?

**Screenshots**
![image](https://github.com/user-attachments/assets/0031f3d1-04fb-41bf-ac4e-5d913e32209e)

**Version:**
 - 2.21.0

**Comment by laggron42** [comment]
Have you edited the file `models.py` or touched anything inside the folder `migrations`?

**Comment by Nipatsu** [comment]
No, I just used git pull and started bot.

**Comment by Nipatsuplayer** [comment]
Okay, I fixed it. It was database problem. I had to edit database manually (postresql)
`ALTER TABLE player ADD COLUMN friend_policy INT DEFAULT 1;`

**Comment by laggron42** [comment]
I'm confused, it is already `DEFAULT 1` in the migrations... @Nipatsu do you still have the issue?

**Comment by Nipatsu** [comment]
No, I fixed it with that command.
