### ISSUE TITLE
Make eval not be able to read config.yml

### ISSUE THREAD

**Issue by OLi51** [Ballsdex-Team/BallsDex-DiscordBot#480]
ctx.bot.http.token does not work but printing out the file directly still works 
![image](https://github.com/user-attachments/assets/d159159c-2090-4120-b11d-4795e96af646)

what would be nice is if I add someone as a co-owner they can't access my config file from evals

**Comment by flaree** [comment]
coowner grants them everything, you should only be granting to to people you trust.

**Comment by OLi51** [comment]
ok :3
