### ISSUE TITLE
[new] Make the bot dm users on blacklist

### ISSUE THREAD

**Issue by imtherealF1** [Ballsdex-Team/BallsDex-DiscordBot#481]
**Describe the feature you'd like**
Send an embed to a user on blacklist. It would include the reason for the blacklist, how to appeal, but maybe not the blacklist user for privacy+safety.

**Additional context**
I have designed and coded that so I can make a PR for it if accepted, and if the user has DMs off then the bot would just  not send anything as is the case right now.

**Comment by flaree** [comment]
Personally not a fan of this, there's plenty of reasons and bulk blacklists I do which I don't  want to be DMd

**Comment by imtherealF1** [comment]
then there could be a boolean argument in blacklist add named `send_dm` or sth, by default True ig
