### ISSUE TITLE
Admin Panel: Load Regimes/Economy - Load start and end date at specials 

### ISSUE THREAD

**Issue by GamingadlerHD** [Ballsdex-Team/BallsDex-DiscordBot#85]
I notice the Regimes and the Economy at the Admin Panel don't load if you want to edit a countryball, so you have to set it every time you edit something on your Countryball. If you forget, it is automaticly set to Democracy and Capitalism. The same is for the start and end date of an special, they are just empty if you edit a countryball.

Woud be nice if you coud add this.

**Comment by laggron42** [comment]
Noticed this and it's definitely annoying, I think this is on [fastapi-admin](https://github.com/fastapi-admin/fastapi-admin), I'll try and see if I can't do something to change this locally.

It's being discussed to completely change the admin panel anyway, as we have a lot of issues with fastapi-admin.

**Comment by laggron42** [comment]
It's been fixed by be58bac51fa24942f48a95768ec736063a9248cc
