### ISSUE TITLE
Localhost:8000

### ISSUE THREAD

**Issue by MonarPio** [Ballsdex-Team/BallsDex-DiscordBot#86]
When I access localhost:8000/admin/init it redirects me to the login page. I don't know if this is normal or not. BTW, post the solution here.

Edit: In the Docker i saw that "303 See Other" and "temporary redirect".

**Comment by flaree** [comment]
Join the self hosted server here: https://discord.gg/M4gVaRrRDe

We no longer support self hosting, someone may help you with your issue here if they know how.
