### ISSUE TITLE
i successfully composed the bot, all checked. commands checked. but when i go to admin panel, i cant click any buttons like "Admins" "Balls" "special", when i clicked them it sad error and does not have authorized. how to fix????

### ISSUE THREAD

**Issue by CommunistDex** [Ballsdex-Team/BallsDex-DiscordBot#93]
please tell me how

**Comment by Bagel-Polygon** [comment]
It appears you might have to go to http://localhost:8000/admin/init to register an admin account for your bot. You will not be able to add anything to your bot unless you do this step.

**Comment by CommunistDex** [comment]
I did go to localhost. Dashboard works. It shows me everything. But when i go to balls, special, admins thing. Does not work, says not authorized. I already put my user id in everything. And also role id. Now what???

**Comment by skyswastaken** [comment]
skill issue tbh

**Comment by skyswastaken** [comment]
reaction spam, really?

**Comment by skyswastaken** [comment]
thats crazy

**Comment by skyswastaken** [comment]
OPPs

**Comment by aIantutorial** [comment]
how dare you delete comments?! 😠

**Comment by aIantutorial** [comment]
my username is SomeRandomDude#8710, go friend me and spam DMs for free cash

**Comment by aIantutorial** [comment]
STUP

**Comment by aIantutorial** [comment]
**_SomeRandomDude#8710 go spam my DMS now before ballsdex people kill me_**

**Comment by NxMXSZ** [comment]
Mx Was Heee

**Comment by flaree** [comment]
Have you created the admin account as stated in the above comment? This is unrelated to what you put in the config.yml
