### ISSUE TITLE
These countryballs didn't show in some servers

### ISSUE THREAD

**Issue by Russente** [Ballsdex-Team/BallsDex-DiscordBot#99]
I'm actually trying to collect these balls using "/balls completion", but there's issue that didn't show in Page 2, and there happened to page 1 when you switched to page 2, So there is issue rn
![image](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/assets/134710511/25ce05f2-82a7-46da-8dba-95bef83549e5)

**Comment by laggron42** [comment]
It's due to a Discord bug, the solution is to give `@everyone` the permission to use external emojis in the channel where the command is used.

You can also give an upvote to this issue, hoping that Discord will fix it some day: https://github.com/discord/discord-api-docs/issues/5279

**Comment by JDJGInc** [comment]
> It's due to a Discord bug, the solution is to give `@everyone` the permission to use external emojis in the channel where the command is used.
> 
> You can also give an upvote to this issue, hoping that Discord will fix it some day: [discord/discord-api-docs#5279](https://github.com/discord/discord-api-docs/issues/5279)

Looking at it for my own bot, it doesn't fix the issue unfortatently
it just seems to have issues with it.
